name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build the Docker image
      - name: Build the Docker image
        run: docker build -t ghcr.io/jacobnollette/github-docker-build:latest .

      # Push the Docker image to GitHub Container Registry
      - name: Push the Docker image
        run: docker push ghcr.io/jacobnollette/github-docker-build:latest
